#  https://docs.github.com/en/actions/guides/publishing-nodejs-packages
# https://github.com/codeforwings/codeforwings/actions
# feels very inefficient to do it this way
# git push --delete origin 0.1.4
name: Node.js Package
on:
  push:
    # or logic. best to leave it with tags only if you dont want it to run
#    branches:
#      - main
#      #      - master
    tags:
      - 0.1.6
    # remember to update package.json and git tags...
#      - ${{version_tag}}
#  release:
#    types: [created]
jobs:
  yarnPublish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
#          # Defaults to the user or organization that owns the workflow file
          scope: 'codeforwings'
      - run: npm i
      - run: npm test
      - run: yarn

#      # Setup .npmrc file to publish to npm
      - run: yarn publish --access public --tag latest dist_npm_package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

#      - run: yarn publish --new-version 0.1.5 --access public --tag latest
#          version: 0.1.5
          # using "Repository secrets"
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
